#server:
#  port: '8082'
#
#spring:
#  profiles:
#    active: dev
#
#---
#
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/dcbapp
#    password: ''
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#  welcome:
#    message: Welcome to SpringBoot Practice!!
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#---
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/dcbapp-qa
#    password: ''
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#  welcome:
#    message: Welcome to SpringBoot Practice!!
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/dcbapp-prod
#    password: ''
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'
#  welcome:
#    message: Welcome to SpringBoot Practice!!

server:
  port: '8082'

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to SpringBoot Practice!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"